Repository teamcubation/byma-sbx-bonos, pull requests merged in 2024-10, with the labels that each got.

#2 Feature/crear proyecto nuevo
  .idea/.gitignore
  .idea/byma-sbx-bonos.iml
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  .mvn/wrapper/maven-wrapper.properties
  HELP.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/services/bono/app/BonoApplication.java
  src/main/java/com/services/bono/app/application/port/in/BonoServicePort.java
  src/main/java/com/services/bono/app/application/port/out/BonoRepositoryPort.java
  src/main/java/com/services/bono/app/application/service/.gitkeep
  src/main/java/com/services/bono/app/domain/model/.gitkeep
  src/main/java/com/services/bono/app/infrastructure/adapter/in/web/.gitkeep
  src/main/java/com/services/bono/app/infrastructure/adapter/out/persistence/entity/.gitkeep
  src/main/java/com/services/bono/app/infrastructure/adapter/out/persistence/mapper/.gitkeep
  src/main/java/com/services/bono/app/infrastructure/adapter/out/persistence/repository/.gitkeep
  src/main/resources/application.properties
  src/test/java/com/services/bono/app/BonoApplicationTests.java
  target/classes/application.properties
Labels: Review effort [1-5]: 4

#4 Feature/implementar controller
  .idea/misc.xml
  .idea/uiDesigner.xml
  pom.xml
  src/main/java/com/services/bond/app/BondApplication.java
  src/main/java/com/services/bond/app/application/port/in/BondInPort.java
  src/main/java/com/services/bond/app/application/port/out/BondOutPort.java
  src/main/java/com/services/bond/app/application/service/.gitkeep
  src/main/java/com/services/bond/app/domain/model/.gitkeep
  src/main/java/com/services/bond/app/domain/model/Bond.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/dto/BondDTO.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/mapper/BondMapper.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/entity/.gitkeep
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/mapper/.gitkeep
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/repository/.gitkeep
  src/main/java/com/services/bono/app/application/port/in/BonoServicePort.java
  src/main/java/com/services/bono/app/application/port/out/BonoRepositoryPort.java
  src/main/java/com/services/bono/app/infrastructure/adapter/out/persistence/repository/.gitkeep
  src/main/resources/application.properties
  src/test/java/com/services/bond/app/BondApplicationTests.java
Labels: Review effort [1-5]: 3

#3 creo entidad, modelo y el mapper correspondiente a los bonos
  src/main/java/com/services/bond/app/BondApplication.java
  src/main/java/com/services/bond/app/application/port/in/BondInPort.java
  src/main/java/com/services/bond/app/domain/model/Bond.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/.gitkeep
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/entity/BondEntity.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/mapper/BondMapper.java
  src/test/java/com/services/bond/app/BonoApplicationTests.java
Labels: Review effort [1-5]: 3

#7 agregado capa aplicacion con service
  .idea/compiler.xml
  src/main/java/com/services/bond/app/application/port/in/BondInPort.java
  src/main/java/com/services/bond/app/application/port/out/BondOutPort.java
  src/main/java/com/services/bond/app/application/service/BondService.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/dto/BondDTO.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/mapper/BondMapper.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/BondPersistenceAdapter.java
  target/classes/application.properties
Labels: Review effort [1-5]: 4

#10 Feature/global exception
  src/main/java/com/services/bond/app/application/port/out/BondOutPort.java
  src/main/java/com/services/bond/app/application/service/.gitkeep
  src/main/java/com/services/bond/app/application/service/BondService.java
  src/main/java/com/services/bond/app/application/service/exception/BondDuplicateException.java
  src/main/java/com/services/bond/app/application/service/exception/BondNotFoundException.java
  src/main/java/com/services/bond/app/domain/model/exception/BondNotFoundException.java
  src/main/java/com/services/bond/app/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/services/bond/app/exceptionHandler/utlis/ErrorMessageResponse.java
  src/main/java/com/services/bond/app/exceptionHandler/utlis/ErrorMessages.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/BondPersistenceAdapter.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/mapper/BondPersistenceMapper.java
Labels: Review effort [1-5]: 4

#11 Se envia ConfigService
  .idea/compiler.xml
  src/main/java/com/services/bond/app/BondApplication.java
  src/main/java/com/services/bond/app/configuration/ConfigService.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/ConfigController.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: Review effort [1-5]: 3

#8 Feature/conectar service con repository y modifcacion de logica de negocios en los metodos
  .idea/misc.xml
  src/main/java/com/services/bond/app/application/port/in/BondInPort.java
  src/main/java/com/services/bond/app/application/port/out/BondOutPort.java
  src/main/java/com/services/bond/app/application/service/BondService.java
  src/main/java/com/services/bond/app/application/service/exception/BondDuplicateException.java
  src/main/java/com/services/bond/app/domain/model/Bond.java
  src/main/java/com/services/bond/app/domain/model/exception/BondDuplicateException.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/BondPersistenceAdapter.java
  src/main/java/com/services/bond/app/infrastructure/adapter/out/persistence/repository/BondRepository.java
Labels: Review effort [1-5]: 4

#9 Se conecta controller con service y se agrega un dto response.
  src/main/java/com/services/bond/app/application/port/in/BondInPort.java
  src/main/java/com/services/bond/app/application/service/BondService.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/dto/request/BondRequest.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/dto/response/BondResponse.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/mapper/BondMapper.java
Labels: Review effort [1-5]: 3

#12 Se verifico la implementacion de las interfaces de puertos y se agregaron mejoras
  .idea/misc.xml
  src/main/java/com/services/bond/app/application/service/BondService.java
  src/main/java/com/services/bond/app/application/service/exception/ValueNegativeException.java
  src/main/java/com/services/bond/app/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/services/bond/app/exceptionHandler/utlis/ErrorMessageResponse.java
  src/main/java/com/services/bond/app/exceptionHandler/utlis/ErrorMessages.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/dto/request/BondRequest.java
  src/test/java/BondApplicationTests.java
  src/test/java/com/services/bond/app/BondApplicationTests.java
Labels: Review effort [1-5]: 4

#13 agrego swagger e implemento interfaces para una mayor modularidad, ag…
  .gitignore
  README.md
  pom.xml
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/ApiBond.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/ApiConfig.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/SwaggerConfig.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/impl/BondController.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/impl/ConfigController.java
  src/main/resources/application.properties
  target/classes/application.properties
Labels: Review effort [1-5]: 3

#16 Se envia el test de BondController
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/impl/BondController.java
  src/main/resources/application.properties
  src/test/java/controller/BondControllerTest.java
  target/classes/application.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: Review effort [1-5]: 4

#15 Feature/testing service
  src/test/java/BondServiceTest.java
Labels: Review effort [1-5]: 4

#14 Se envia Dockerfile
  Dockerfile
Labels: Review effort [1-5]: 2

#17 Se corrige error de respuesta en el metodo register del controlador y…
  src/main/java/com/services/bond/app/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/services/bond/app/exceptionHandler/utlis/ErrorMessages.java
  src/main/java/com/services/bond/app/infrastructure/adapter/in/web/controller/impl/BondController.java
Labels: Review effort [1-5]: 2
